# Default values for simple-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: zipik/nodjs-server
  pullPolicy: IfNotPresent
  tag: "latest"

  
port: 80
host: site3
