apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    run: {{ .Release.Name }}
spec:
  ports:
  - protocol: TCP
    targetPort: 2021
    port: {{ .Values.port }}
  selector:
    app: {{ .Release.Name }}