name: test
on:
  push:
    branches: [ main ]
jobs:
  kaniko-build-push-docker-hub:
    runs-on: k8s-runner
    container: 
     image: gcr.io/kaniko-project/executor:v1.14.0-debug
    steps:
      - name: add Docker Hub credentials
        run: |
            mkdir -p /kaniko/.docker
            echo "{\"auths\":{\"https://index.docker.io/v1/":{\"username\":\"${{ secrets.DOCKERHUB_USERNAME }}",\"password\":\"${{ secrets.DOCKERHUB_TOKEN }}"}}}" > /kaniko/.docker/config.json
            /kaniko/executor --context "$(pwd)" --dockerfile "$(pwd)/Dockerfile" --destination "docker.io/zipik/nodjs-server:${CIRCLE_SHA1}"
