name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: k8s-runner
    container:
       image: gcr.io/kaniko-project/executor:debug
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for dockerenv file
        run: |
          pwd
          ls -l
          sleep 300
