---
name: Example 2
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build Docker
    runs-on: k8s-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
      

