name: Publish Docker image

on: push
env:
  NAMESPACE: test1
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: k8s-runne-dind
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: test
        run: |
          echo ${{ github.run_number }}
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zipik/nodjs-server:${{ github.run_number }}
deploy-job:
    name: Deploy and running nodejs app
    runs-on: k8s-runne
    container: alpine/helm:3.14.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy helm
        run: |
          helm upgrade --install nodejs-server --set image.tag=${{ github.run_number }} .\helm-app\ --namespace test1 --create-namespace
