name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: k8s-runne-dind
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

